version: '3'

services:
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    ports:
      - 8080:8080
    # uncomment if you want to submit work from outside the docker network
    #      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    depends_on:
      - spark-master
    ports:
      - 8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  notebook:
    # get to the notebook via
    # http://<hostname>:8888/?token=<token>
    # check the notebook logs for the token or for the direct link
    image: jupyter/pyspark-notebook:7a0c7325e470
    depends_on:
      - spark-master
    container_name: notebook
    ports:
      - 8888:8888
    environment:
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/ipython
    volumes:
      - notebook-data:/home/jovyan

volumes:
  notebook-data:
